version: '3'

services:
  traefik:
    image: traefik:v2.2.0
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config:/etc/traefik/config
      - ./certs:/etc/certs
    labels:
      traefik.http.routers.redirect.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.redirect.entrypoints: web
      traefik.http.routers.redirect.middlewares: redirect-to-https
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https

networks:
  proxy:
    external: true
