global:
  sendAnonymousUsage: false

log:
  level: 'DEBUG'

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ':80'
  https:
    address: ':443'

providers:
  docker: {}
  file:
    directory: '/etc/traefik/config'
    watch: true
